name = "daimond113/lexi_workspace"
private = true
version = "0.1.0"
license = "MIT"
workspace_members = ["pkgs/*"]

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
darklua = { name = "pesde/darklua", version = "^0.17.1", target = "lune" }

[engines]
lune = "^0.10.2"
